name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        git clone https://github.com/wspl/CIDR2PAC.git
        cd ./CIDR2PAC
        wget -O- 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > cn-aggregated.zone.txt
        npm install
        node ./
      env:
        CI: true
        
    - name: Prepare artifact
      run: rm -rf {./CIDR2PAC/whitelist.pac}
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: whitelist
        path: ./CIDR2PAC/
